spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 74110asd123.
    url: jdbc:mysql://127.0.0.1:3306/smarthr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 47.112.105.123
    publisher-returns: true
    publisher-confirm-type: correlated
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
#    password: 74110asd123.
    timeout: 60s
    lettuce:
      cluster:
        refresh:
          adaptive: true
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10

  cache:
    cache-names: menus_withRole_cache
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
      enabled: true
  mvc:
    async:
      request-timeout: 10000

server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/

aliyun:
  oss:
    shenzhenEndpoint: oss-cn-shenzhen.aliyuncs.com # oss深圳对外服务的访问域名
    endpoint: oss.smartsoftware.top # oss cdn加速域名
    accessKeyId: LTAI4GC3GWTFECczVmxmb1aA # 访问身份验证中用到用户标识
    accessKeySecret: NkYLqwYScPJrnJ7IPFHX5MEeVHvfgi # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: 826076402 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 500 # 上传文件大小(M)
    callback: http://hr.smartsoftware.top/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: cloud   # 上传文件夹路径前缀

cloudmarket:
  ocr:
    appCode: db1a233f30294d4093afa7ce51b19440
    appKey: 203931139
    appSecret: jp2PhssBxgYe0m4sihD69nkpgfXo1IIa
    idCardUrl: https://dm-51.data.aliyun.com/rest/160601/ocr/ocr_idcard.json
    bankCardUrl: https://yhk.market.alicloudapi.com/rest/160601/ocr/ocr_bank_card.json
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
